### ISSUE TITLE
Duplicate Badges 

### ISSUE THREAD

**Issue by santiagogm1995** [SAP-samples/devtoberfest-2021#39]
Hi experts! 

I was doing some of the tutorials marked for devtoberfest and in some cases I have been assigned a duplicate badge for the same tutorial. 

For example:  

https://developers.sap.com/tutorials/btp-app-launchpad-service.html

#5DAEBC - Devtoberfest 2021 - Add the SAP Launchpad Service
#6B1572 - Devtoberfest 2021 - Add the SAP Launchpad Service

Another question, do all tutorials award points? Or only the ones completed during devtoberfest?

Id: santiago_gonzalez_mota80

Thank you and best regards!!!

**Comment by jung-thomas** [comment]
I've asked someone from the team to check those two badges you mention.  It could be a cut and paste error with the description, but we will find out.  Thanks for reporting that.

>do all tutorials award points?
No, not all tutorials. Each week we will release a list of tutorials that match up to the topic of that particular week. Only those sub-set of tutorials will earn you points.  However, if you have already completed any of these tutorials ahead of time; you still get points credit for them.  We didn't want to people to miss out just because they had already done certain tutorials in the past. Therefore you retroactively get points for them.  You probably are even seeing points and badges for tutorials in weeks we've not announced yet. But you can check back each week on the contest page to get the new list of tutorials for that week. https://github.com/SAP-samples/devtoberfest-2021/tree/main/contest#points-earning-activities-by-week  Week two will be uploaded soon.
